# WorkFlow
name: Github Action 실행시켜보기

on:
  push:
    branchers: -main

# workflow는 여러개의 jpb로 이루어 질수 있다.
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    # 하나의 jpb는 여러개의 step으로 이루어져 있다.
    steps:
      - name: Hello World 출력하기
        run: echo "Hello World"

      - name: 여러 명렁어 문장 작성하기
        run: |
          echo "Hi"
          echo "안녕"
          pwd
